### ISSUE TITLE
Problem with 'filterQuery

### ISSUE THREAD

**Issue by christhoph** [RyanNHG/one-north-demo#1]
When I perform a search, it appears in console:

> [Vue warn]: Computed property "filterQuery" was assigned to but it has no setter.

What could be the problem?

Good tutorial, good luck.

Cristopher Solis.

**Comment by ryan-haskell** [comment]
Hey @christhoph !

Great catch! The error was caused by my use of `v-model` on the input field.

Instead of doing a two-way data-bind (updating `filterQuery` when input changes, as well as updating the input when the `filterQuery` changes) with `v-model`, I should have been using `v-bind:value`.

`v-bind:value` has a one-way data binding, meaning changing the input will not update the `filterQuery`. In this case, that's what we want, because computed properties should be read-only.

`v-model` should only be set on `data` properties on our Vue apps!

Here's the commit where I fixed the issue: https://github.com/RyanNHG/one-north-demo/commit/9d03e7a94109aa8e7d4296ef9f43a9136b0974be

Thanks for the feedback,
Ryan
